angular.module('zfpxchat',['ngRoute','angularMoment']).config(function($locationProvider,$routeProvider){
    $locationProvider.html5Mode(false);
    $routeProvider.when('/',{
        templateUrl:'pages/room.html',
        controller:'RoomCtrl'
    }).when('/login',{
        templateUrl:'pages/login.html',
        controller:'LoginCtrl'
    }).when('/reg',{
        templateUrl:'pages/reg.html',
        controller:'RegCtrl'
    }).otherwise({
        redirectTo:'/'
    });
});

angular.module('zfpxchat').run(function(validator,$location){
    validator.then(function(){
        $location.path('/');
    },function(){
        $location.path('/login');
    });
});